on:
  repository_dispatch:
    types: [spec_release]
  workflow_dispatch:
#on: push

name: Generate VRChat API SDK

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate VRChat API SDK
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Test Image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: vrchatapi-php:development
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max

      - name: Generate SDK Client
        run: |
          docker run --rm vrchatapi-php:development generate

      - name: Check version number
        run: |
          echo "spec_version=$(grep \"The version of the OpenAPI document:\" ./lib/Configuration.php | head -n 1 | cut -d \":\" -f 2)" >> $GITHUB_ENV

      - name: Print version number
        run: echo ${{ env.spec_version }}

      - name: Deploy SDK back into main branch
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main
          folder: .
          commit-message: "Upgrade PHP SDK to spec ${{ env.spec_version }}"
